### ISSUE TITLE
Checklist for 2.0

### ISSUE THREAD

**Issue by DrChainsaw** [DrChainsaw/NaiveNASlib.jl#86]
With #40 potentially being solved it might be feasible to go for #41. Since #41 is breaking I'll just list a few things in there which I would also like to change for 2.0 to minimize risk of forgetting them.

By judging from the influx of issues I'm probably the only user of this package and therefore I'm planning to be quite liberal with breakage. Hopefully the end result is a leaner, more idiomatic API which is easier to use. If you are user of this package and don't want unnecessary breakage then please let me know.

- [x] [Remove size state](https://github.com/DrChainsaw/NaiveNASlib.jl/issues/41)
- [x] Remove the min delta factor functions
- [x] Add bangs to mutating methods
- [x] Add support for Functors.jl
- [x] Remove most of the pretty printing and vertex formatting stuff
- [x] Remove dependencies to LightGraphs and MetaGraphs
- [x] Remove export of internal/special purpose functions
